version: '2'

services:
    proxy:
        build:
            context: .
            dockerfile: Dockerfile-proxy
        links:
            - app
        ports:
            - "8080:8080"
    app:
        build:
            context: .
            dockerfile: Dockerfile-app
        links:
            - redis
        ports:
            - "3000:3000"
    redis:
        image: redis
        ports:
            - "6379:6379"