FROM    centos:centos6

# Enable EPEL for Node.js
RUN     rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm

# Install Node.js and npm
RUN     yum install -y npm

# Bundle app source
COPY ./App /App

# Install app dependencies
RUN cd /App; npm install

EXPOSE 8080 3000-3005 6379
CMD ["node", "/App/app.js"]